apiVersion: v1
kind: Service

metadata:
  name: kubernetes-platform-service

spec:
  type: NodePort

  selector:
    app: kubernetes-platform

  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30080
